name: my_portfolio_website
description: "Personal portfolio website"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter  
  flutter_web_plugins:
    sdk: flutter
  provider: ^6.1.2
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.2
  animated_text_lerp: ^2.0.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  flutter_native_splash: ^2.4.6
  auto_route: ^10.1.2
  slang: ^4.10.0
  slang_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.7.0
  auto_route_generator: ^10.2.4
  slang_build_runner: ^4.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/null_end_browser/
    - assets/easy_pgp/
    - assets/horizon/
    - assets/bm/
    - assets/kami/
    - assets/null_end_vpn/
    - assets/papi_burgers/
    - assets/taxi_app/
    - assets/blog/
    - assets/avatar.png
    - assets/me.png
    - assets/me2.jpg
    - lib/about_me/about.json

flutter_native_splash:
  color: "#000000" # Set splash screen background color (black)
  image: assets/avatar.png # Path to your logo image (make sure it is in the assets folder)
  web: true # Enable splash screen for Web (only works in some cases)
